const SERVER_URL = 'http://localhost:8000'
const CONNECTION_STATUS = {
    CONNECTING: 'CONNECTING',
    CONNECTED: 'CONNECTED',
    DISCONNECTED: 'DISCONNECTED',
}
const RECORDING_STATUS = {
    RECORDING: 'RECORDING',
    PAUSED: 'PAUSED',
    STOPED: 'STOPED',
}
const CAPTURE_DEVICE_STATUS = {
    CONNECTED: 'CONNECTED',
    CONNECTING: 'CONNECTING',
    DISCONNECTED: 'DISCONNECTED',
}

export {
    SERVER_URL,
    CONNECTION_STATUS,
    RECORDING_STATUS,
    CAPTURE_DEVICE_STATUS,
}